# Generated by Django 3.2.6 on 2021-08-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_rename_cvr_url_ebook_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='cover_url',
            field=models.CharField(max_length=5000000),
        ),
    ]
