# Generated by Django 3.2.6 on 2021-08-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='cover_url',
        ),
    ]
